name: fitness-app

services:
  db:
    container_name: fitness-app-database
    image: postgres:16
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
